// src/components/EssentialList.vue
<template>
  <q-expansion-item :icon="`sym_r_${essentialLink.meta.icon}`" :label="$t(`page.${essentialLink.name}`)">
    <div v-for="link in essentialLink.children" :key="link.id" class="q-ml-md">
      <!-- children -->
      <EssentialList v-if="link.children && link.children.length > 0" :essentialLink="link"
        :parent-path="pathResolve(parentPath, link.meta.path)" />

      <!-- single item -->
      <EssentialLink v-else
        v-bind="{ name: link.name, icon: link.meta.icon, path: link.meta.path, parentPath: parentPath || '' }" />
    </div>
  </q-expansion-item>
</template>

<script setup lang="ts">
import EssentialLink from 'components/EssentialLink.vue'
import type { PrivilegeTreeNode } from 'src/types'
import { pathResolve } from 'src/utils'

withDefaults(defineProps<{
  essentialLink: PrivilegeTreeNode
  parentPath?: string
}>(), {
  parentPath: ''
})
</script>

// src/components/EssentialList.tsx
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router'
import { PanelMenu } from 'primereact/panelmenu'
import { retrievePrivilegeTree } from 'src/api/privileges'
import { pathResolve } from 'src/utils'
import type { PrivilegeTreeNode } from 'src/types'
import type { MenuItem } from 'primereact/menuitem'



const recursion = (nodes: PrivilegeTreeNode[], navigate: Function, parentPath: string = "/"): MenuItem[] => {
  return nodes.map(node => {
    const menuItem: MenuItem = {
      label: node.name,
      icon: `pi pi-${node.meta.icon}`,
      items: node.children ? recursion(node.children, navigate, pathResolve(parentPath, node.meta.path)) : undefined,
      // template: itemRenderer
    }
    if (!node.children || node.children.length === 0) {
      menuItem.command = () => { navigate(pathResolve(parentPath, node.meta.path)); };
    }

    return menuItem
  })
}

function EssentialList() {
  const navigate = useNavigate()
  const [privileges, setPrivileges] = useState<PrivilegeTreeNode[]>([])

  useEffect(() => {
    retrievePrivilegeTree().then(res => {
      if (res) {
        setPrivileges(res);
      }
    })
  }, [])

  const items = recursion(privileges, navigate)

  return (
    <PanelMenu model={items} />
  )
}

export default EssentialList
